[project]
name = "pedro-harvey"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "apscheduler>=3.11.2",
    "asyncpg>=0.31.0",
    "click>=8.4.0",
    "dotenv>=0.9.9",
    "greenlet>=3.5.1",
    "holidays>=0.97",
    "httpx>=0.28.1",
    "lightgbm>=4.6.0",
    "matplotlib>=3.10.9",
    "pandas>=3.0.3",
    "psycopg2>=2.9.12",
    "scikit-learn>=1.8.0",
    "sqlalchemy>=2.0.49",
]
